<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>orc</string>
		<string>inc</string>
	</array>
	<key>name</key>
	<string>Orc</string>
	<key>scopeName</key>
	<string>source.orc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.orcdoc</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-dash.orc</string>
			<key>begin</key>
			<string>--</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.orc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.orc</string>
			<key>begin</key>
			<string>\{-</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.orc</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
			</array>
			<key>end</key>
			<string>-\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.orc</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.orc</string>
			<key>match</key>
			<string>\b(val|def|site|class|type)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.extends.orc</string>
			<key>match</key>
			<string>\b(extends|with)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.include.orc</string>
			<key>match</key>
			<string>\b(include)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.import.orc</string>
			<key>match</key>
			<string>\b(import)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.orc</string>
			<key>match</key>
			<string>\b(else|if|then)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.new.orc</string>
			<key>match</key>
			<string>\b(new)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.underscore.orc</string>
			<key>match</key>
			<string>\b(_)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.orc</string>
			<key>match</key>
			<string>\b(this|super)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.stop.orc</string>
			<key>match</key>
			<string>\b(stop)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.orc</string>
			<key>match</key>
			<string>\b(signal|false|true|null)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>([0-9]+)([.][0-9]+)?([Ee][+-]?([0-9]+))?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.orc</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.orc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.orc</string>
					<key>match</key>
					<string>(\\u[0-9A-Fa-f]{4}|\\.)</string>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.orc</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.arithmetic.orc</string>
			<key>match</key>
			<string>(\*\*|\+|-|\*|/|%)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.orc</string>
			<key>match</key>
			<string>(&amp;&amp;|\|\||~)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignment.orc</string>
			<key>match</key>
			<string>(:=|\?)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.orc</string>
			<key>match</key>
			<string>(&lt;:|:&gt;|&lt;=|&gt;=|/=|=)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.pattern.as.orc</string>
			<key>match</key>
			<string>\b(as)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.separator.value-type.orc</string>
			<key>match</key>
			<string>(::|:!:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.cons.orc</string>
			<key>match</key>
			<string>(:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.dereference.orc</string>
			<key>match</key>
			<string>(\.)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.combinator.orc</string>
			<key>match</key>
			<string>(\{\||\|\}|&gt;|\||;)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.section.paren.orc</string>
			<key>match</key>
			<string>(\(|\))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.section.bracket.orc</string>
			<key>match</key>
			<string>(\[|\])</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.section.record.orc</string>
			<key>match</key>
			<string>(\{\.|\.\})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.section.brace.orc</string>
			<key>match</key>
			<string>(\{|\})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.separator.definition.orc</string>
			<key>match</key>
			<string>(\#)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.separator.arguments.orc</string>
			<key>match</key>
			<string>(,)</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment_block</key>
		<dict>
			<key>name</key>
			<string>comment.block.orc</string>
			<key>begin</key>
			<string>\{-</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.orc</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
			</array>
			<key>end</key>
			<string>-\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.orc</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>uuid</key>
	<string>6E085ECB-F472-4291-A1BF-BCA22378FF83</string>
</dict>
</plist>
